<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id$
*/
return array (
'about'=>'Acerca De',
'action'=>'Acción|Acciones',
'activa'=>'Activa',
'activo'=>'Activo',
'add'=>'Agregar',
'advancedSearch'=>'Búsqueda Avanzada',
'advancedWebInterface'=>'Interfaz Web Avanzada',
'advancedWebInterfaceSlogan'=>'Velocidad web en tus objetivos',
'advancedWebInterfaceDesc'=>'Data Models y Data Mining serán verdaderamente efectivos en la medida que cuenten con procesos de publicación, distribución y navegación en entornos colaborativos diseñados a la medida de los diferentes equipos de trabajo en una empresa. iSeeCI ofrece con la Interfaz Web Avanzada una plataforma de colaboración corporativa que mejorará en gran medida el conocimiento del negocio por parte de los directivos y el personal, optimizada en términos objetivos de ejecución de tareas (GOMS).',
'blog'=>'Blog|Blogs',
'caption'=>'Subtítulo|Subtítulos',
'client'=>'Cliente',
'code'=>'Codigo',
'comparisonSearch'=>'Puedes ingresar un operador de comparación (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) al principio de los valores para especificar la comparación a realizar.',
'contact'=>'Contacto',
'contactus'=>'Contáctanos',
'content'=>'Contenido|Contenidos',
'corporateIdentity'=>'Identidad Corporativa',
'create'=>'Crear',
'dateTime'=>'Fecha-Hora',
'dashboard'=>'Tablero de Control|Tableros de Control',
'dashboardSlogan'=>'Mejor conocimiento de sí mismo',
'dashboardDesc'=>'Para la toma de decisiones es fundamental contar con una herramienta que refleje indicadores propios de la gestión del negocio. El Tablero de Control que ofrece iSeeCI es el sistema ideal para acompañar la Toma de Decisiones ya que cuenta con diversos indicadores prestablecidos y un conjunto seleccionado de indicadores para cada negocio, con el fin de que no se escape ni un detalle.',
'dataMining'=>'Data Mining',
'dataWarehousing'=>'Almacenamiento de Datos',
'dataModels'=>'Data Models',
'delete'=>'Eliminar',
'description'=>'Descripción|Descripciones',
'doubts'=>'Si tienes alguna duda o sugerencia acerca de nuestros servicios, no dudes en contactarnos.',
'element'=>'Elemento|Elementos',
'elemento'=>'Elemento|Elementos',
'email'=>'Correo Electrónico',
'facebookFeed'=>'Feed de Facebook de iSeeCI',
'forecasting'=>'Proyección',
'googleTechNews'=> 'Noticias Tech de Google',
'googleNews'=> 'Noticias de Google',
'home'=>'Inicio',
'image'=>'Imagen',
'intelligentDashboard'=>'Tablero Inteligente|Tableros Inteligentes',
'intelligentDashboardSlogan'=>'Más allá de la información',
'intelligentDashboardDesc'=>'Algunas veces los indicadores de siempre simplemente no muestran información contundente y se debe recurrir a otro tipo de indicadores. iSeeCI provee la automatización de búsqueda de indicadores a través de heurísticos basados en comportamientos naturales como Algoritmos Evolutivos, PSO, Colonias de Abejas ... para su posterior publicación en el Tablero de Control.',
'interested'=>'Interesado|Interesados',
'lastQuote'=>'Cotización Anterior',
'lineOfBusiness'=>'Línea de Negocio',
'list'=>'Lista|Listas',
'link'=>'Link|Links',
'login'=>'Entrar',
'loginFacebook'=>'Haz login con Facebook para interactuar con las publicaciones de esta página',
'manage'=>'Administrar',
'menu'=>'Menú|Menus',
'message'=>'Mensaje|Mensajes',
'name'=>'Nombre|Nombres',
'news'=>'Noticias',
'objectAttachment'=>'Anexo|Anexos',
'operation'=>'Operación|Operaciones',
'optimization'=>'Optimización',
'optimizationSlogan'=>'Porque todo puede ser mejor',
'optimizationDesc'=>'Los procesos de una compañía deben estar en continua optimización pues todos los días surgen nuevas herramientas para la producción. iSeeCI ofrece su experiencia en la formulación y solución de problemas de optimización tales como Programación Lineal, Rutas Mínimas, Problemas Combinatoriales, Frontera Eficiente, Teoría de Colas, Modelos de Pérdida ... y así estar siempre un paso delante de los competidores.',
'overdue'=>'Vencida',
'page'=>'Página|Páginas',
'parent'=>'Padre',
'password'=>'Contraseña',
'pathImage'=>'Dirección Imagen',
'picture'=>'Imagen',
'picURL'=>'URL Imagen',
'presentation'=>'<p>Cuando las buenas ideas surgen, sean negocios, proyectos, 
			productos, procesos y demás, 
			requieren de un universo de elementos para cumplir sus objetivos y 
			ser exitosas.</p>
			<p>iSee Corporate Intelligence se vale de técnicas avanzadas de Inteligencia Artificial,
			soportadas en una Plataforma Tecnológica de punta que en conjunto
			con modelos Estadísticos y Matemáticos del estado del arte, nos permiten
			ofrecer a nuestros clientes gran facilidad para acceder
			no solo a la información generada, sino a valioso conocimiento
			extraído de la misma. En términos prácticos mayor certeza al momento de tomar decisiones, un contacto más cercano con los grupos de interés y por ende un alto retorno sobre la inversión.</p>
			<p><b>iSeeCI ofrece acompañamiento integral a sus clientes en el desarrollo y crecimiento de sus buenas ideas.</b></p>',
'position'=>'Posición',
'publish'=>'Publicar',
'quote'=>'Cotización|Cotizaciones',
'quoteStatus'=>'Estado Cotización',
'relationalDataModel'=>'Modelo de Datos Relacional',
'relationalDataModelSlogan'=>'Lo que tienes y cómo lo tienes',
'relationalDataModelDesc'=>'Si se busca orden, trazabilidad y escalabilidad es necesario un Sistema de Información capaz de reflejar fielmente la operación de una empresa. iSeeCI provee el desarrollo, despliegue y sostenimiento de RDBMS con la mejor calidad en términos de optimización de espacio y accesibilidad.',
'rememberMe'=>'Recordarme',
'replaced'=>'Reemplazada',
'requirement'=>'Requerimiento|Requerimientos',
'rights'=>'Todos los derechos reservados',
'rootElement'=>'[Raíz]',
'save'=>'Guardar',
'segmentation'=>'Segmentación|Segmentaciones',
'segmentationSlogan'=>'Tu información como nunca la viste',
'segmentationDesc'=>'Para la gestión de clientes, proveedores e inventarios, una Segmentación Inteligente es la clave. iSeeCI pone a disposición de sus clientes modelos de última generación como SOM, PCA-SOM, Redes Neuronales, Fuzzy C-Means ... con el objetivo de apoyar de manera sistematizada la toma de decisiones.',
'send'=>'Enviar',
'SEO'=>'SEO',
'SEOSlogan'=>'Nunca te conocerán lo suficiente',
'SEODesc'=>'Actualmente la web es una combinación inevitable entre los sitios existentes y el índice o buscador que se usa para encontrarlos. Una buena posición en estos índices garantiza muchos más visitantes a un sitio y por ende mayor impacto. iSeeCI ofrece toda su experiencia en el desarrollo paralelo de descripciones y meta-tags en lugares estratégicos de la Aplicación Web para así Optimizarla en Motores de Búsqueda.',
'stochasticSimulation'=>'Simulación Estocástica|Simulaciones Estocásticas',
'stochasticSimulationSlogan'=>'Los fenómenos desde adentro',
'stochasticSimulationDesc'=>'La realidad y el porvenir de una compañía así como el comportamiento de sus procesos dependen de muchos factores, algunos de ellos aleatorios. Cuando los modelos determinísticos no son útiles, iSeeCI provee herramientas para la parametrización, la simulación y los reportes de Escenarios Estocásticos con el fin de obtener no sólo un resultado sino también su sensibilidad a eventos fortuitos y / o catastróficos.',
'subtitle'=>'Subtítulo',
'sureDelete'=>'Estás seguro de borrar este elemento?',
'techInfraestructure'=>'Infraestructura|Infraestructuras',
'techInfraestructureSlogan'=>'Recursos justo a la medida',
'techInfraestructureDesc'=>'La elección correcta a la hora de implementar un modelo de datos para la compañía depende de diversos factores como el tamaño, la geolocalización, sus metas y objetivos ... iSeeCI brinda asesoría en la evaluación, adquisición, instalación e implementación de la Infraestructura necesaria para llevar a cabo un Modelo de Datos Relacional.',
'term'=>'Plazo',
'thanxContact'=>'Gracias por contactarnos. Le responderemos lo más pronto posible.',
'title'=>'Título|Títulos',
'totalValue'=>'Valor Total',
'typeElement'=>'Tipo de Elemento',
'update'=>'Editar',
'userNoPages'=>'El usuario no tiene paginas de Facebook.',
'validity'=>'Vigencia',
'view'=>'Ver',
'webDevelopment'=>'Web Development',
'webHosting'=>'Web Hosting',
'webIntelligence'=>'Inteligencia Web',
'webSite'=>'Sitio Web|Sitios Web',
'webSiteSlogan'=>'Abre tu mente a la web',
'webSiteDesc'=>'Cualquier organización desea sobre todo dar a conocer - y por supuesto vender - sus productos y servicios. Qué mejor manera de hacerlo que través de la web y llegar a consumidores en todos los rincones del mundo? iSeeCI ofrece con su solución Sitio Web, un portal desarrollado a la medida para compartir toda la información de interés entre organización, clientes y proveedores.',
);
